# Generated by Django 4.0.3 on 2022-03-10 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='SOME STRING', max_length=80),
        ),
    ]
